version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=wedding.settings.test
