version: '3.6'

services:
  web:
    image: noslouch/wedding-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=wedding.settings.test
