version: '3.6'

services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: noslouch/wedding-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=wedding.settings.test

volumes:
  postgres_data:
