
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "9a:90:64:46:38:b2:ef:ad:55:e6:0e:36:a2:e4:e0:26"
      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: build image
          command: docker build -t noslouch/wedding-api .
      - run:
          name: 🚢 it
          command: docker push noslouch/wedding-api
      - run:
          name: setup envvars
          command: |
            ssh-keyscan melissaandbriangetmarried.com >> ~/.ssh/known_hosts
            env | sed -n 's/DEPLOY_//p' > .env
            scp .env bwhitton@melissaandbriangetmarried.com:~
      - run:
          name: pull down image and start with envvars
          command: |
            ssh bwhitton@melissaandbriangetmarried.com -v "docker pull noslouch/wedding-api"
            ssh bwhitton@melissaandbriangetmarried.com -v "docker stop wedding-api && docker rm wedding-api"
            ssh bwhitton@melissaandbriangetmarried.com -v "docker run \
                                                        --name wedding-api \
                                                        --restart always \
                                                        --env-file ~/.env \
                                                        -p 8000:8000 \
                                                        -d \
                                                        -t noslouch/wedding-api"
