# Generated by Django 2.1 on 2018-08-16 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('cmmr', 'Cmmr.')], max_length=4)),
                ('wedding_rsvp', models.BooleanField(null=True)),
                ('rehearsal_rsvp', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehearsal_dinner', models.BooleanField()),
                ('address', models.TextField()),
                ('music_pref', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Invitation'),
        ),
    ]
