# Generated by Django 2.1 on 2018-08-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='plus_one',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
