# Generated by Django 2.1 on 2018-08-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_invitation_plus_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='plus_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='rehearsal_dinner',
            field=models.BooleanField(default=False),
        ),
    ]
