# Generated by Django 2.1 on 2018-08-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20180817_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='title',
        ),
        migrations.AlterField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.Invitation'),
        ),
    ]
