# Generated by Django 2.1 on 2018-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20180817_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='sunday_brunch',
            field=models.BooleanField(null=True),
        ),
    ]
