# Generated by Django 2.1 on 2018-08-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_guest_sunday_brunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
